<?php
/**
 * Default configuration (safe for local XAMPP use).
 * For a live website, DO NOT edit this file: copy config.local.example.php to
 * config.local.php and put your real settings there. It overrides these values.
 */
return [
    'app_name'    => 'SGVMS',
    'school_name' => 'Sample Elementary School',
    'timezone'    => 'Asia/Manila',

    // true  = demo mode: sample-data banner, demo login hints, "Reset demo logs" button.
    // false = production: all demo helpers are hidden/disabled.
    'demo_mode'   => true,

    // true  = show detailed errors (development). false = generic error page (production).
    'debug'       => true,

    'db' => [
        'host'    => 'localhost',
        'port'    => 3306,
        'name'    => 'sgvms',
        'user'    => 'root',   // XAMPP default. Use a dedicated limited user online.
        'pass'    => '',       // XAMPP default is empty. Use a strong password online.
        'charset' => 'utf8mb4',
    ],

    // Sign-in protection: lock after this many failed tries within the window.
    'login_max_attempts'   => 5,
    'login_window_minutes' => 10,
];
